# Generated by Django 4.1.2 on 2024-07-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mce', '0002_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default=56, max_length=5),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
